version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.3.6

executors:
  default-ubuntu:
    machine:
      image: ubuntu-2004:202309-01

jobs:
  build:
    docker:
      - image: golang:1.23.3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod tidy
      - run:
          name: Run Tests
          command: go test ./...
      - run:
          name: Build Application
          command: go build -o bank-ifsc main.go

  deploy:
    docker:
      - image: golang:1.23.3
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          create-repo: true
          repo: "${CIRCLE_PROJECT_REPONAME}"
          region: ${AWS_REGION}
          tag: "${CIRCLE_BUILD_NUM}"
          context: imrkgofficial
          
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
