version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.23.3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod tidy
      - run:
          name: Run Tests
          command: go test ./...
      - run:
          name: Build Application
          command: go build -o bank-ifsc main.go

  deploy:
    docker:
      - image: golang:1.23.3
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: |
            echo "Deploying application..."
            # Add your deployment steps here (e.g., deploy with Docker/Portainer)

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build