name: Build to AWS ECR

on: push

jobs:
  login-to-aws:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v4

    - name: Login to AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}
        
  build-and-push-pub-ecr:
    runs-on: ubuntu-latest
    needs: login-to-aws

    steps:
    - name: Code Checkout
      uses: actions/checkout@v4

    - name: Login to AWS ECR
      uses: docker/login-action@v3
      with:
        registry: public.ecr.aws
        username: ${{ secrets.ACCESS_KEY }}
        password: ${{ secrets.SECRET_ACCESS_KEY }}
      env:
        aws-region: ${{ secrets.PUBLIC_REGION }}

    - name: Build and Push Image
      run: |
        docker build -t bank .
        docker tag bank:latest public.ecr.aws/h8o8x8t1/bank:v11
        docker push public.ecr.aws/h8o8x8t1/bank:v11

  build-and-push-private-ecr:
    runs-on: ubuntu-latest
    needs: login-to-aws

    steps:
    - name: Code Checkout
      uses: actions/checkout@v4

    - name: Login to AWS ECR
      uses: docker/login-action@v3
      with:
        registry: 637423205071.dkr.ecr.ap-south-1.amazonaws.com
        username: ${{ secrets.ACCESS_KEY }}
        password: ${{ secrets.SECRET_ACCESS_KEY }}

    - name: Build and Push Image
      run: |
        docker build -t bank .
        docker tag bank:latest 637423205071.dkr.ecr.ap-south-1.amazonaws.com/bank:v11
        docker push 637423205071.dkr.ecr.ap-south-1.amazonaws.com/bank:v11
